model_type: VICReg
n_steps: 17
val_n_steps: 17
dataset_size: 10000
dataset_noise: 0.5
val_dataset_size: 10000
wandb: true
run_name: sweep_changing_structured.(0.5).idm.93
run_group: sweep_changing_structured.(0.5).idm
output_path: null
safe_every_n_epochs: 10
eval_mpcs: 20
quick_debug: false
seed: 1
load_checkpoint_path: null
eval_only: false
probe_mpc: false
dataset_static_noise: 0.0
dataset_structured_noise: true
dataset_structured_noise_path: /scratch/us441/datasets/cifar
dataset_batch_size: 64
dataset_static_noise_speed: 0.0
dataset_dot_std: 1.3
dataset_normalize: true
vicreg:
  projector: id
  random_projector: false
  predictor: rnn
  backbone_mlp: null
  sim_coeff: 0.0
  std_coeff: 0.0
  cov_coeff: 0.0
  encoding_std_coeff: 0.0
  encoding_cov_coeff: 0.0
  decoding_coeff: 0.0
  action_coeff: 0.11886454311483488
  prediction_diff_coeff: 0.0
  arch: menet5
  epochs: 100
  base_lr: 0.5595321193403839
  repr_loss_after_projector: false
  skip_first_step_vc: true
  embedding_size: 512
  action_dim: 2
  rnn_layers: 1
  backbone_width_factor: 2
  rnn_burnin: 1
  channels: 1
rssm:
  backbone_width_factor: 1
  action_coeff: 0.0
  arch: resnet18
  epochs: 100
  learning_rate: 0.001
  embedding_size: 64
  action_dim: 2
  min_var: 0.1
  rssm_adam_epsilon: 1.0e-08
  log_recontructed_image: true
  channels: 1
  rnn_burnin: 1
simclr:
  projector: 512-512-512
  random_projector: false
  predictor: rnn
  backbone_mlp: null
  epochs: 100
  base_lr: 0.2
  decoding_coeff: 0.0
  action_coeff: 0.0
  arch: menet5
  embedding_size: 64
  action_dim: 2
  rnn_layers: 1
  rnn_burnin: 1
  backbone_width_factor: 1
  normalize_z: false
  loss_temp: 1.0
  channels: 1
vjepa:
  arch: vit
  predictor:
    embed_dim: 32
    depth: 6
    num_heads: 4
    mlp_ratio: 4
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    patch_size: 4
  encoder:
    embed_dim: 64
    depth: 12
    num_heads: 4
    mlp_ratio: 4
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    patch_size: 4
eval_at_the_end_only: true
dataset_type: Single
probing_cfg:
  full_finetune: false
  lr: 0.001
  epochs: 30
  epochs_enc: 30
  schedule: null
  prober_arch: ''
