model_type: VJEPA
n_steps: 18
val_n_steps: 18
dataset_size: 10000
dataset_noise: 0.25
val_dataset_size: 10000
wandb: true
run_name: null
run_group: null
output_path: models/vjepa/changing_structured.(0.25)/
safe_every_n_epochs: 10
eval_mpcs: 20
quick_debug: false
seed: 1
load_checkpoint_path: null
eval_only: false
probe_mpc: false
dataset_static_noise: 0.0
dataset_structured_noise: true
dataset_structured_noise_path: /tmp/cifar
dataset_batch_size: 128
dataset_static_noise_speed: 0.0
dataset_dot_std: 1.3
dataset_normalize: true
vicreg:
  projector: id
  random_projector: false
  predictor: rnn
  backbone_mlp: null
  sim_coeff: 4.55420869645181
  std_coeff: 1.025714924330587
  cov_coeff: 1.0
  encoding_std_coeff: 0.0
  encoding_cov_coeff: 0.0
  decoding_coeff: 0.0
  action_coeff: 0.0
  prediction_diff_coeff: 0.0
  arch: menet5
  epochs: 100
  base_lr: 0.47041252015562457
  repr_loss_after_projector: false
  skip_first_step_vc: true
  embedding_size: 512
  action_dim: 2
  rnn_layers: 1
  backbone_width_factor: 2
  rnn_burnin: 1
  channels: 1
rssm:
  backbone_width_factor: 1
  action_coeff: 0.0
  arch: resnet18
  epochs: 100
  learning_rate: 0.001
  embedding_size: 64
  action_dim: 2
  min_var: 0.1
  rssm_adam_epsilon: 1.0e-08
  log_recontructed_image: true
  channels: 1
  rnn_burnin: 1
simclr:
  projector: 512-512-512
  random_projector: false
  predictor: rnn
  backbone_mlp: null
  epochs: 100
  base_lr: 0.2
  decoding_coeff: 0.0
  action_coeff: 0.0
  arch: menet5
  embedding_size: 64
  action_dim: 2
  rnn_layers: 1
  rnn_burnin: 1
  backbone_width_factor: 1
  normalize_z: false
  loss_temp: 1.0
  channels: 1
hjepa:
  arch: vit
  masking_ratio: 0.7
  img_size: 28
  patch_size: 4
  tubelet_sizes: [2, 6]
  num_frames: 18
  channels: 1
  epochs: 100
  base_lr: 0.09040525
  ema: [0.998, 1.0]
  ipe: 78  # Same as dataset_size / batch size
  ipe_scale: 1.25
  predictor_embed_dim: 32
  predictor_depth: 3
  predictor_num_heads: 4
  predictor_mlp_ratio: 4
  predictor_qkv_bias: true
  predictor_drop_rate: 0.0
  predictor_attn_drop_rate: 0.0
  predictor_drop_path_rate: 0.0
  encoder_embed_dim: 64
  encoder_depth: 6
  encoder_num_heads: 4
  encoder_mlp_ratio: 4
  encoder_qkv_bias: true
  encoder_drop_rate: 0.0
  encoder_attn_drop_rate: 0.0
  encoder_drop_path_rate: 0.0
eval_at_the_end_only: true
dataset_type: Single
probing_cfg:
  full_finetune: false
  lr: 0.001
  epochs: 30
  epochs_enc: 30
  schedule: null
  prober_arch: ''
